name: Market CI

on:
  push:
    branches: [ "*" ]
    paths:
      - market/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install protobuf-compiler
      run: sudo apt update && sudo apt install -y protobuf-compiler
    - name: Build
      run: cd market && cargo build --verbose
  test:
    name: Test Market
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cd market && cargo test --verbose
  format:
    name: Format Market
    if: ${{ !contains(github.event.head_commit.message, 'GITHUB ACTIONS') }}
    uses: ./.github/workflows/fmt.yml # use current repo's fmt.yml
    with:
      config-path: "market"
    